[build]
  command = "npm run build"
  publish = "dist" # or "build" for CRA

# Enable clean single-page routing (important for React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
